### ISSUE TITLE
Support for private git sources

### ISSUE THREAD

**Issue by jonahweissman** [wojciechkepka/pkger#57]
Thanks for creating this awesome project!

I'm hoping to use pkger to build packages that are hosted on a private git server. Based on my understanding, the easiest way for me to do this right now would be to include my SSH key that is authorized to access the git server in my docker image. However, this is a little messy and could create security issues. It seems like [forwarding the SSH agent](https://stackoverflow.com/a/36648428) to the docker container would be the right way to do this. What do you think?

**Comment by vv9k** [comment]
Thanks for checking it out!

I do agree that moving the private key to the container would potentially open up more security holes than forwarding the SSH agent from the host. From the replies it looks like it works both on Linux and MacOS so seems like a viable approach to me.

**Comment by vv9k** [comment]
If you find any issues with the current implementation please report back. I only tested it briefly by doing a simple ssh to a server that had my key as authorized and it worked correctly.

**Comment by jonahweissman** [comment]
Thanks for adding that so quickly!

I had been using v0.3.0, but after building from master, I'm getting this:
```
ERROR  job failed, id=pkger-decide-linux-armv7a-1626447460, reason=invalid type: null, expected a sequence at line 1 column 4312, duration=0.6212626s
```
It seems like an error with `docker-api-rs` because a git bisect indicated that the problem started with commit 0e39655a69d20ee4537363a1c7966a8913e45c61.

I'd be happy to move that to another issue, but I can't test the SSH agent forwarding until I can find a work around.

**Comment by vv9k** [comment]
Would you be able to rerun the job with tracing enabled a.k.a `RUST_LOG=docker_api=trace` and submit the message that fails to get parsed as a bug report to `docker_api`? If not then perhaps could you point out what method returns the invalid message?

**Comment by vv9k** [comment]
Thanks for submitting the issue! I think it should be resolved now. Let me know how the tests go :)

**Comment by jonahweissman** [comment]
Thanks for fixing that so quickly!

The SSH forwarding seems to work great! However, because git clone is being run in a non-interactive setting, the host key verification  fails (i.e. no input is given to "Are you sure you want to continue connecting (yes/no/[fingerprint])?"). It works if I add
```
env:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=accept-new
```
but there might be a better way to do this. Also, git clone seems to direct its output to stderr, so the messages appear as "ERROR" in the rust log.

**Comment by vv9k** [comment]
#60 should resolve your issues. You can now add this to your configuration:
```yaml
ssh:
  forward_agent: true
  disable_key_verification: true
```

I also plan to add a way to upload `authorized_keys` to the container in #61 so that the connections can be more secure.

EDIT:
I meant `known_hosts` of course.

**Comment by jonahweissman** [comment]
> #60 should resolve your issues.

It works perfectly! Thanks so much.

> I also plan to add a way to upload `known_hosts` to the container in #61 so that the connections can be more secure.

I think this is a good idea.
