### ISSUE TITLE
pkger build: no recipes to build

### ISSUE THREAD

**Issue by jonahweissman** [wojciechkepka/pkger#63]
Running `pkger build` produces:
```
WARN  no recipes to build
```
However, `pkger list recipes` outputs a non-empty list. I can share the whole trace from `pkger build`, but it seems like the important part is just this:
```
TRACE opts=Opts {
    quiet: false,
    debug: false,
    trace: true,
    filter: None,
    config: None,
    command: Build(
        BuildOpts {
            recipes: [],
            simple: None,
            images: None,
            docker: None,
            all: false,
            no_sign: false,
        },
    ),
}
```

**Comment by vv9k** [comment]
I think this is desired behavior, but perhaps could be better documented. Previously `pkger build` would build all recipes for all image targets and that is something not everyone expects as it might lead to a lot of builds started without the users intent. Right now if you want to build all images you have to explicitly add `pkger build --all` or specify the recipes that you want to build `pkger build recipe1 recipe2...`

**Comment by jonahweissman** [comment]
Okay, that makes sense. I'm not quite sure where I got the impression that it would build everything. Maybe `pkger build` could output the intended usage if invoked without any recipes or flags?

**Comment by vv9k** [comment]
That does sound like a good idea, I added initial warning message in #68. Do you think this message is enough or should it display some more usage options?

**Comment by jonahweissman** [comment]
Looks perfect! Thank you
