### ISSUE TITLE
pkger silently fails to apply patches (uses wrong location)

### ISSUE THREAD

**Issue by lukasz-e** [wojciechkepka/pkger#90]
### Environment

- Platform: Linux (ubuntu 20.04), docker 20.10.21 in rootless mode
- pkger version: pkger 0.10.0

<details>
recipe contains list of patches like:
<pre>
  patches:
    - gcc11-alt-compat-test.patch
    - gcc11-d-shared-libphobos.patch
   ...
</pre>
During build I can see in output:
<pre>
[INFO ][2022-12-01T18:08:10.576Z][sfx-gcc11][11.3.0][rocky8] applying patches
[ERROR][2022-12-01T18:08:10.599Z][sfx-gcc11][11.3.0][rocky8] /bin/sh: /tmp/sfx-gcc11-tmp-1669918080/patches/gcc11-alt-compat-test.patch: No such file or directory
[WARN ][2022-12-01T18:08:10.600Z][sfx-gcc11][11.3.0][rocky8] applying patch Patch { patch: "gcc11-alt-compat-test.patch", strip: 0, images: None } failed, reason = command failed with exit code 1
Error:
/bin/sh: /tmp/sfx-gcc11-tmp-1669918080/patches/gcc11-alt-compat-test.patch: No such file or directory
...
</pre>
... and so on for all patches.
And build continues like nothing wrong happened.

As I looked into container, patches are uploaded to /tmp/sfx-gcc11-tmp-1669918080/patches.tar/ directory, /tmp/sfx-gcc11-tmp-1669918080/patches is empty
I see 2 problems here:

1. patches are uploaded or fetched to/from wrong location in container
2. failure during patch apply does not stop build => it can be easy overlooked

</details>

**Comment by lukasz-e** [comment]
first part of problem (using wrong patch location) is probably in pkger-core/src/build/patches.rs:87 - fix here made patches work

**Comment by vv9k** [comment]
Should be resolved in #91. I'll leave the issue open for now to confirm that it works on your end.
