### ISSUE TITLE
rpmspec crate

### ISSUE THREAD

**Issue by dralley** [wojciechkepka/pkger#94]
Sorry, this is an awkward way to reach out, but the email listed on your github didn't work and your website appears to be down.

I noticed that you have ownership of the "rpmspec" crate but that the crates got yanked and the repository deleted.

https://crates.io/crates/rpmspec

I'm curious if you would be OK with allowing us to use the crate name, and potentially continue maintaining your library?

We're working on a specfile parsing library and "rpmspec" is the most obvious name.  But making a building *and* parsing library would be great, too, and we'd be interested in continuing your work on that portion also.

https://github.com/rpm-rs/rpmspec-rs

If you would rather not, that is perfectly OK (of course).  But if you're not using it and it's something you're open to, let me know.  Thanks.

- Daniel

**Comment by dralley** [comment]
@vv9k ^

**Comment by vv9k** [comment]
Hello,

Sure thing, I'd be up to transfer the rights to the crate name. I'm not really used to this process so do I have to add someone as an owner of the crate or what exactly are the steps to accomplish this?

**Comment by dralley** [comment]
I *think* you go on crates.io to your crate (https://crates.io/crates/rpmspec), make sure you're logged in, go to "settings", and add github usernames there with whichever permissions you want.

**Comment by vv9k** [comment]
I've sent you an invite to add a new owner to this crate

**Comment by dralley** [comment]
Thanks!  Do you want to stay on the list as an owner?

**Comment by vv9k** [comment]
Feel free to remove me :) good luck with the project!
